SimpleBlog.PL/Controllers/BlogPostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.BLL.Models;
using SimpleBlog.BLL.Services;
using SimpleBlog.DAL.Entities;

namespace SimpleBlog.PL.Controllers
{
    public class BlogPostController : Controller
    {
        private readonly IBlogRepo blogRepo;
        private readonly IMapper mapper;

        public BlogPostController(IBlogRepo blogRepo, IMapper mapper)
        {
            this.blogRepo = blogRepo;
            this.mapper = mapper;
        }

        public async Task<IActionResult> GetData(string titlesearch)
        {
            if (titlesearch == null)
            {
                var data = await blogRepo.GetAsync();
                var result = mapper.Map<IEnumerable<BlogPostVM>>(data);
                return View(result);
            }
            else
            {
                var data = await blogRepo.GetAsync(bp => bp.Title.Contains(titlesearch));
                var result = mapper.Map<IEnumerable<BlogPostVM>>(data);
                return View(result);
            }

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BlogPostVM blogPost)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<BlogPost>(blogPost);
                    await blogRepo.CreateAsync(data);
                    return RedirectToAction("GetData");
                }
                return View(blogPost);
            }
            catch (Exception ex)
            {
                return View(blogPost);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detalis(int id)
        {
            try
            {
                var data = await blogRepo.GetByAsync(bp => bp.Id == id);
                var result = mapper.Map<BlogPostVM>(data);
                return View(result);
            }
            catch (Exception ex)
            {
                return View($"Error : {ex.Message}");
            }

        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var data = await blogRepo.GetByAsync(bp => bp.Id == id);
            var result = mapper.Map<BlogPostVM>(data);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(BlogPostVM blogPost)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<BlogPost>(blogPost);
                    await blogRepo.UpdateAsync(data);
                    return RedirectToAction("GetData");
                }
                return View(blogPost);
            }
            catch
            {
                return View(blogPost);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var data = await blogRepo.GetByAsync(bp => bp.Id == id);
            var result = mapper.Map<BlogPostVM>(data);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(BlogPostVM blogPost)
        {
            try
            {
                var data = mapper.Map<BlogPost>(blogPost);
                await blogRepo.DeleteAsync(data);
                return RedirectToAction("GetData");
            }
            catch (Exception ex)
            {
                return View(blogPost);
            }
        }

        public IActionResult About()
        {
            return View();
        }


    }
}

SimpleBlog.PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SimpleBlog.PL.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

SimpleBlog.PL/Views/BlogPost/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}

<div class="hero-wrap js-fullheight" style="background-image: url(images/bg_1.jpg);" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="js-fullheight d-flex justify-content-center align-items-center">
		<div class="col-md-8 text text-center">
			<div class="img mb-4" style="background-image: url(images/MyPhoto.jpg);"></div>
			<div class="desc">
				<h2 class="subheading">Hello I'm</h2>
				<h1 class="mb-4">Adel Mohamed</h1>
				<p class="mb-4">I am a student at the Faculty of Science, in the fourth year, Department of Mathematics and Computer Science. I specialize in the field of software and work as a back-end programmer for websites.</p>
				<ul class="ftco-social mt-3">
					<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
					<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
					<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
		
	

	

SimpleBlog.PL/Views/BlogPost/Create.cshtml
@model BlogPostVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}

<style>
    textarea {
        width: 100%;
        max-width: 700px;
        height: 200px;
        padding: 10px;
        border: 2px solid #4CAF50;
        border-radius: 10px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        color: #333;
        background-color: #f9f9f9;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        resize: none;
    }

        textarea:focus {
            border-color: #2ECC71;
            outline: none;
            box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
        }

        textarea::placeholder {
            color: #999;
            font-style: italic;
        }

    input {
        padding: 10px;
        border: 2px solid #4CAF50;
        border-radius: 10px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        color: #333;
        background-color: #f9f9f9;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        resize: none;
    }

        input:focus {
            border-color: #2ECC71;
            outline: none;
            box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
        }

        input::placeholder {
            color: #999;
            font-style: italic;
        }
</style>

<section class="ftco-section">
	<div class="container">
		<div>
            
            <h1><a href="index.html">NEW BLOG<span>.</span></a></h1>
            <br />
            <br />
            <form asp-controller="BlogPost" asp-action="Create" class="form-group">
                <br />
                <label asp-for="Title">Title</label>
                <br />
                <input type="text" asp-for="Title"  placeholder="Enter Title Max 100 Character" class="form-control" />
                <span asp-validation-for="Title" class="text-danger font-bold"></span>
                <br />
                <label asp-for="Content">Content</label>
                <br />
                <textarea asp-for="Content" placeholder="Enter blog Content"></textarea>
                <br />
                <span asp-validation-for="Content" class="text-danger font-bold"></span>
                <br />
                <label asp-for="AutherName">Auther Name</label>
                <br />
                <input type="text" asp-for="AutherName" placeholder="Enter Auther Name Max 50 Character " class="form-control" />
                <span asp-validation-for="AutherName" class="text-danger font-bold"></span>
                <br />
                <center>
                    <input type="submit" value="Save" class="btn btn-success" />
                    <input type="reset" value="Reset" class="btn btn-warning" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-danger">Cancel</a>
                </center>
            </form>
		</div>
	</div>
</section>

@section JqueryValidation{
    <script src="~/js/jquery-validate/jquery.validate.js"></script>
    <script src="~/js/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/js/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

SimpleBlog.PL/Views/BlogPost/Delete.cshtml
@model BlogPostVM
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}

<style>
    textarea {
        width: 100%;
        max-width: 700px;
        height: 200px;
        padding: 10px;
        border: 2px solid #4CAF50;
        border-radius: 10px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        color: #333;
        background-color: #f9f9f9;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        resize: none;
    }

        textarea:focus {
            border-color: #2ECC71;
            outline: none;
            box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
        }

        textarea::placeholder {
            color: #999;
            font-style: italic;
        }

    input {
        padding: 10px;
        border: 2px solid #4CAF50;
        border-radius: 10px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        color: #333;
        background-color: #f9f9f9;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        resize: none;
    }

        input:focus {
            border-color: #2ECC71;
            outline: none;
            box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
        }

        input::placeholder {
            color: #999;
            font-style: italic;
        }
</style>

<section class="ftco-section">
    <div class="container">
        <div>
            <h1><a href="index.html">DELET BLOG<span>.</span></a></h1>
            <br />
            <br />
            <form asp-controller="BlogPost" asp-action="Delete" class="form-group">
                <br />
                <input asp-for="Id" type="hidden" class="form-control" />
                <label asp-for="Title">Title</label>
                <br />
                <input type="text" asp-for="Title" placeholder="Enter Title Max 100 Character" class="form-control" readonly />
                <br />
                <label asp-for="Content">Content</label>
                <br />
                <textarea asp-for="Content" placeholder="Enter blog Content" readonly></textarea>
                <br />
                <br />
                <label asp-for="AutherName">Auther Name</label>
                <br />
                <input type="text" asp-for="AutherName" placeholder="Enter Auther Name Max 50 Character " class="form-control" readonly />
                <br />
                <center>
                    <input type="submit" value="Delete" class="btn btn-success" />
                    <a asp-controller="BlogPost" asp-action="GetData" class="btn btn-danger">Cancel</a>
                </center>
            </form>
        </div>
    </div>
</section>

SimpleBlog.PL/Views/BlogPost/GetData.cshtml
@model IEnumerable<BlogPostVM>

@{
    ViewData["Title"] = "GetData";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}


<style>
    tbody, thead, tr, th, td {
        text-align: center !important;
    }
</style>
<section class="ftco-section">
    <div class="container">
        <div>
            <div>
                <form asp-controller="BlogPost" asp-action="GetData" class="container-fluid">
                    <div class="row">
                        <div class="col-lg-10">
                            <input type="text" placeholder="Search by title" class="form-control" name="titlesearch" />
                        </div>
                        <div class="col-lg-2">
                            <input type="submit" value="Search" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
            <br />
            <br />
            <div id="datasearch">
                <table class="table table-bordered table-striped table-hover font-weight-bold">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Auther Name</th>
                            <th>CreatedDate</th>
                            <th>Details</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Title</td>
                                <td>@item.AutherName</td>
                                <td>@item.CreatedDate.ToLongDateString()</td>
                                <td><a asp-controller="BlogPost" asp-action="Detalis" asp-route-id="@item.Id" class="btn btn-success">Details</a></td>
                                <td><a asp-controller="BlogPost" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Update</a></td>
                                <td><a asp-controller="BlogPost" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>

        </div>
    </div>
</section>
@section AjaxSearch{
    <script>
        $(document).ready(function () {
            $('#searchform').submit(function (e) {
                e.preventDefault();
                var query = $('#titlesearch').val();
        
                $.ajax({
                    url: '@Url.Action("GetData", "BlogPost")',  
                    type: 'GET',
                    data: { title: query },  
                    success: function (result) {
                                        $('#datasearch').html(result);
                        },
                    error: function () {
                        alert("An error occurred while searching. Please try again.");
                    }
                });
            });
        });
    </script>
}

SimpleBlog.PL/Views/BlogPost/Update.cshtml
@model BlogPostVM
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}

<style>
    textarea {
        width: 100%;
        max-width: 700px;
        height: 200px;
        padding: 10px;
        border: 2px solid #4CAF50;
        border-radius: 10px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        color: #333;
        background-color: #f9f9f9;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        resize: none;
    }

    textarea:focus {
        border-color: #2ECC71;
        outline: none;
        box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
    }

    textarea::placeholder {
        color: #999;
        font-style: italic;
    }

    input {
        padding: 10px;
        border: 2px solid #4CAF50;
        border-radius: 10px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        color: #333;
        background-color: #f9f9f9;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        resize: none;
    }

    input:focus {
        border-color: #2ECC71;
        outline: none;
        box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.2);
    }
    input::placeholder {
        color: #999;
        font-style: italic;
    }
</style>
<section class="ftco-section">
    <div class="container">
        <div>
            <h1><a href="index.html">EDIT BLOG<span>.</span></a></h1>
            <br />
            <br />
            <form asp-controller="BlogPost" asp-action="Update" class="form-group">
                <br />
                <input asp-for="Id" type="hidden" class="form-control" />
                <input asp-for="CreatedDate" type="hidden" class="form-control" />
                <label asp-for="Title">Title</label>
                <br />
                <input type="text" asp-for="Title" placeholder="Enter Title Max 100 Character" class="form-control" />
                <span asp-validation-for="Title" class="text-danger font-bold"></span>
                <br />
                <label asp-for="Content">Content</label>
                <br />
                <textarea asp-for="Content" placeholder="Enter blog Content"></textarea>
                <br />
                <span asp-validation-for="Content" class="text-danger font-bold"></span>
                <br />
                <label asp-for="AutherName">Auther Name</label>
                <br />
                <input type="text" asp-for="AutherName" placeholder="Enter Auther Name Max 50 Character " class="form-control" />
                <span asp-validation-for="AutherName" class="text-danger font-bold"></span>
                <br />
                <center>
                    <input type="submit" value="Save" class="btn btn-success" />
                    <input type="reset" value="Reset" class="btn btn-warning" />
                    <a asp-controller="BlogPost" asp-action="GetData" class="btn btn-danger">Cancel</a>
                </center>
            </form>
        </div>
    </div>
</section>

@section JqueryValidation {
    <script src="~/js/jquery-validate/jquery.validate.js"></script>
    <script src="~/js/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/js/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

SimpleBlog.PL/Views/Layout/MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
	<link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <div id="colorlib-page">
        <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
        <aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
            <h1 id="colorlib-logo"><a href="index.html">BLOGS<span>.</span></a></h1>
            <nav id="colorlib-main-menu" role="navigation">
                <ul>
                    <li class="colorlib-active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="BlogPost" asp-action="GetData">Blogs</a></li>
                    <li><a asp-controller="BlogPost" asp-action="Create">Create Blog</a></li>
                    <li><a asp-controller="BlogPost" asp-action="About">About</a></li>
                </ul>
            </nav>

            <div class="colorlib-footer">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | To Services Blogs
                    <ul>
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-instagram"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    </ul>
            </div>
        </aside> <!-- END COLORLIB-ASIDE -->
        <div id="colorlib-main">
            @RenderBody()
            @RenderSection("Footer", false)
        </div><!-- END COLORLIB-MAIN -->
    </div><!-- END COLORLIB-PAGE -->
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>
    <script src="~/js/jquery.min.js"></script>
	@RenderSection("JqueryValidation",false)
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.timepicker.min.js"></script>
    <script src="~/js/scrollax.min.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/main.js"></script>
	@RenderSection("AjaxSearch",false)
</body>
</html>